[phases.setup]
nixPkgs = ["python39", "gcc", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
